server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/operis-project?serverTimezone=UTF
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect:
code:
  secret: csjkcna+ewefnfnwp=foepqnccnsdjcnoauenfajvnanivaa-we0wfnokecocnds

logging:
  level:
    root: INFO
    com.operis: INFO
